### ISSUE TITLE
won't let me put negative values in to take away some of the review days I added

### ISSUE THREAD

**Issue by neuroblastommy** [Arthur-Milchior/Anki-postpone-reviews#2]
messed up and added 2 days to ALL reviews rather than the decks I needed to postpone. I have to review cards for my test in 2 days and just read the deal about the code messing up if I try to custom study and review ahead. what should I do??

**Comment by neuroblastommy** [comment]
@Arthur-Milchior @jasonsparc plz halp

**Comment by neuroblastommy** [comment]
This is the error report I get when I try to input "-1"
I've also tried "- 1" , "negative 1" , "(1)" , "(-1)" and "neg 1" but these return "please enter an integral number of days"

Error 
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
Debug info:
Anki 2.1.11 (3cf770c7) Python 3.6.7 Qt 5.12.1 PyQt 5.11.3
Platform: Mac 10.14.2
Flags: frz=True ao=True sv=1
Add-ons possibly involved: Postpone cards review

Caught exception:
  File "/Users/tpm59458/Library/Application Support/Anki2/addons21/1152543397/__init__.py", line 66, in <lambda>
    a.triggered.connect(lambda : runBrowser(browser))
  File "/Users/tpm59458/Library/Application Support/Anki2/addons21/1152543397/__init__.py", line 61, in runBrowser
    addDelay(cids)
  File "/Users/tpm59458/Library/Application Support/Anki2/addons21/1152543397/__init__.py", line 43, in addDelay
    card.ivl += max(0,round(delay * (getIntervalCoefficient() if delay >0 else getIntervalForNegativeCoefficient())))
<class 'NameError'>: name 'getIntervalForNegativeCoefficient' is not defined

**Comment by jasonsparc** [comment]
I think, the [warning](https://github.com/Arthur-Milchior/Anki-postpone-reviews#warning) about filtered decks in the `README` file is outdated.

In the new update, there is no longer any harm if you have filtered decks or reviewing ahead, their card's due and intervals will get updated accordingly if you use the add-on. Although, the cards and the order of the cards under any existing filtered decks (those already there before you used the add-on) will still be the same. If you don't personally want that, you have to press “rebuild” on those filtered decks, but be careful not to do so if you already have pending *learning* cards under those filtered decks, as they would get reset (turned into review cards again) if you do a “rebuild” (as noted in the Anki manual) on such filtered decks.

As for the crashing, I have looked into the code. It's just a simple fix and I'll be creating a pull-request to help out, as it seems very urgent.

**Comment by neuroblastommy** [comment]
Thank you so much! I downloaded the add-on yesterday too, so idk if there's any outdated stuff unless it wasn't added into a recent edit. Since I have that final exam on Friday, I have the option to manually reschedule and move all the cards in my deck for the final that I should've been seeing today, tomorrow, and friday morning by ahead 2 days (to effectively cancel the mistake out), but that will reset all of their intervals to 1 day... 

Will your fix allow me to reset their due dates to take away the 2 days I added to the deck I need?

**Comment by neuroblastommy** [comment]
also, just for a quick bit of info: i'm not tech-smart AT ALL, so when you comment back with the fix, could you tell me how to implement any changes? Thank you again very much

**Comment by jasonsparc** [comment]
@neuroblastommy No worries, I'm already planing of doing that 😉

**Comment by jasonsparc** [comment]
And btw, for your last question, the add-on is designed to adjust all intervals and due dates for all cards of all decks, not just for specific decks. So, sorry if I can't help you with that. One hypothetical future enhancement is to probably allow for something like a *per deck postponement* but that'll probably require a big change.

With the upcoming fix though, if you input `-2`, then it should undo all the changes you did when you inputted `2` before, provided that you also toggled on a special feature called something like `"coefficient for negative"` – which I'll explain later how you'll be able to do so…

**Comment by neuroblastommy** [comment]
perfect, thank you

and in regards to that, I had meant that I added 2 days to all reviews, but the add-on also lets me change the scheduling for single specific cards if I just manually select them. I'd just go into my gastrointestinal subdeck and select all of those for the final 😅

**Comment by jasonsparc** [comment]
Forget my last comment, screw the part where I said:

> One hypothetical future enhancement is to probably allow for something like a *per deck postponement* but that'll probably require a big change.

…and let's pretend that I never said that 😆

**Comment by neuroblastommy** [comment]
regardless of fine-tuning it, would those 3 fixes you changed to the coding technically solve my problem in the short-term? as in, if I opened __init__.py and config.json and threw in those changes at least to solve my immediate problem, would that ruin my entire anki system?

b/c i'm in a bit of a time crunch and I can just throw in those changes, fix the problem quick, then check back in the next day or two and re-download the updated version to make sure it's fine-tuned for future use. What do you think?

**Comment by neuroblastommy** [comment]
as in I have the raw file versions of your updates open and I can replace the existing ones with your updates if you think they'll work

**Comment by jasonsparc** [comment]
It should fix your problem :)

For your convenience, here's the zip file:

https://github.com/jasonsparc/Anki-postpone-reviews/archive/feature/issue%232-fix-neg-error.zip

Download it, extract it, replace the files in the add-on folder, open Anki, go to the add-on's interface, select the add-on, press “config” then set `"coefficient for negative"` to `true`. And you're all set!

No worries about messing your Anki system.

**Comment by jasonsparc** [comment]
^ And of course, restart Anki first before using the add-on again, after doing all the steps I mentioned you should do above…

**Comment by jasonsparc** [comment]
@neuroblastommy Possibly, 2 restarts: one is after replacing the files in the add-on's folder, and the other is after tinkering with the “config” to set `"coefficient for negative"` to `true`.

**Comment by neuroblastommy** [comment]
it worked perfectly!!! thank you so much for helping so quickly

**Comment by Arthur-Milchior** [comment]
Your commit is now online. The addon can be updated. Sorry for the trouble.

As a more general advice, I should advise @neuroblastomy to make back up before trying a new add-on (i.e. by synchronizing, or restarting anki.) So you can back up if required. 

Thank you @jasonsparc for your help. It's quite nice to figure out that I don't have to spend time myself on this.

**Comment by neuroblastommy** [comment]
that I did, and the patch is perfect. I honestly can't thank you two enough for getting this done so fast. My deck, my grade, and my ass all thank you for saving them.
