### ISSUE TITLE
I updated my postpone cards add on today (1/28/21) and it wont work!

### ISSUE THREAD

**Issue by AM202118** [Arthur-Milchior/Anki-postpone-reviews#21]
An add-on you installed failed to load. If problems persist, please go to the Tools>Add-ons menu, and disable or delete the add-on.

When loading '⁨Postpone cards review⁩':
⁨Traceback (most recent call last):
  File "aqt/addons.py", line 211, in loadAddons
  File "/Users/aysswaryamanoharan/Library/Application Support/Anki2/addons21/1152543397/__init__.py", line 1, in <module>
    from . import addToBrowser, addToGear, addToMain
  File "/Users/aysswaryamanoharan/Library/Application Support/Anki2/addons21/1152543397/addToGear.py", line 2, in <module>
    from aqt.hooks_gen import deck_browser_will_show_options_menu
ModuleNotFoundError: No module named 'aqt.hooks_gen'

**Comment by AM202118** [comment]
I have Anki 2.1.29

**Comment by BPBWBC** [comment]
im having the same problem as well!

**Comment by brunchlord** [comment]
I'm having the same issue. Any way to revert back to the old add on?

**Comment by 1928492** [comment]
Same issue over here. version 2.1.26

**Comment by rumDMC** [comment]
On 2.1.35 with the same issue. Love the addon, thanks for all you do!

**Comment by AM202118** [comment]
yes, its fixed ! thank you for everything !
