### ISSUE TITLE
Quick question: Bringing back the following day's reviews?

### ISSUE THREAD

**Issue by Z1839** [Arthur-Milchior/Anki-postpone-reviews#4]
Hey, i'm not sure how to message you directly so i'm posting it here. Basically, I was wondering if there was a way to bring back the day that was shifted when I delayed the current day's reviews?

In other words, let's say I have 200 reviews left at the end of the day and postpone them to the next day. The next day i'll just have those 200 reviews due. Let's say I finish the 200 reviews and want to continue that next day that was moved over, is there a way to do this with the addon that would "bring back" the original schedule, or do I need to make a filtered deck?

**Comment by Arthur-Milchior** [comment]
You can use the same add-on, and enter «-1» to state to move everything backward one day.
Is this what you wanted to do ?

**Comment by Z1839** [comment]
Ah, I thought that would do it, but I wasn’t sure if it would bring everything back one day. I thought it would bring everything from today back.

**Comment by Arthur-Milchior** [comment]
I'm not entirely sure about what you means. 
I fear that you are partially right.
It removes a day from everything. Which means in particular it removes a day from cards you saw today.
If a card you saw today was planned for tomorrow, it is then again planned for today. Sadly, it seems hard to avoid this problem. I don't know what exactly the add-on should do in this case. Or how you'd configure the add-on to obtain perfectly what you want.

However, if you saw a card today and it is planned in 10 days, then you'll see it in 9 days instead. Which does not seem to be a big issue I believ

**Comment by Arthur-Milchior** [comment]
Do you have nay answer or update ? Otherwise I'll close this issue.
