### ISSUE TITLE
Post pone add on

### ISSUE THREAD

**Issue by sahmed251** [Arthur-Milchior/Anki-postpone-reviews#41]
Hi, I am unable to install the add- on for the latest version of Anki. It is giving me an error whenever I place the code in and press install.

**Comment by Arthur-Milchior** [comment]
is this resolved? I see you closed the issue @sahmed251 
I admit I don't understand your bug report, so will need more details.
I assume by "the code" you mean the add-on number, in the add-on manager.
What occurs after you install and restart?
