### ISSUE TITLE
How to postpone all cards including ones that are in "learning" stage?

### ISSUE THREAD

**Issue by shayandavoodii** [Arthur-Milchior/Anki-postpone-reviews#44]
How to postpone all cards including ones that are in "learning" stage?

**Comment by alvneb** [comment]
I found a way to fix it. Just replace the file "addDay.py" with this:

[addDay.zip](https://github.com/user-attachments/files/16549614/addDay.zip)

**Comment by Arthur-Milchior** [comment]
I admit this was not something I had in mind sorry. Those, in theory, you really should not postpone them. I'm not sure I want to edit the add-on more for this
