### ISSUE TITLE
Cards I postponed are not coming back

### ISSUE THREAD

**Issue by mahsan95** [Arthur-Milchior/Anki-postpone-reviews#5]
Hi, 

So I have a bunch of decks for each big block of testing I have in school. I postponed the cards for my reviews of old tests, but kept the reviews for my current test active. I set it for 2 days on Wednesday (May 15th), knowing on Friday they'd come back. This wasn't the case, and the cards just aren't coming back! I tried going to those specific decks and adding negative numbers in to speed up the process, but instead, it somehow glitches and brings back cards into that one deck I was studying for, not the deck I'm clicking on. I'm getting frustrated because i need to do those review cards for my big cumulative test coming up.

Please help me fix this!

**Comment by Arthur-Milchior** [comment]
Let me try to understand what you did exactly.
Wensday, you opened the browser. You selected the deck "old tests", you then selected all card, and postponed all of them by 2 days.
Normally, the cards which were due wensday would now be seen as due, friday. And only those cards. Any other cards from the "old tests", which were dues thursday or latzr, should not be seen friday, since you added two days to them

Do you mean you didn't see friday the cards you should have seen wensday according to anki ? In this case, something went wrong

**Comment by Arthur-Milchior** [comment]
It may be easier to understand what's wrong if you give name to every deck.right now, I don't know whether "that one deck I was studying for" is the same than "current test" or "old test" or something else.
Do you mean that, after you selected cards and added "-2" days to them, the number of due card augmented and the new due cards are cards you didn't s3lect . I don't see how it could be possible

**Comment by mahsan95** [comment]
Yes, let me explain it better.

So, we have huge block tests since January. They’re called Comps.

I have a Comp 1 deck, a Comp 2 deck, and a Comp 3 (current stuff) deck. Each Comp deck is filled with 2 Mid Comp decks (which are essentially mini tests between the block exams). I just had a mid comp from Comp 3 on Friday, so I went to my Comp 1/2 and one mid comp deck from prior and suspended them. Each time going to every deck and hitting postpone for 2 days on Wednesday. Come Friday, none of them showed back up. Okay, so I hit -1 day to bring it back, nope, it only brought back the reviews for Mid Comp that I was studying for. I kept trying different variations, doing -2 (seeing that only impact the deck I studied for) and then +2 to undo that. 

So eventually, I just decided maybe they’ll come back at ONE point or another. But that’s still kind of stressful with the studying I have to do.

**Comment by mahsan95** [comment]
The midcomp decks I was referring to were Midcomp 5 and Midcomp 6. Midcomp 6 was what I was studying for, Mid comp 5 was the one I didn’t need at the moment, but need now.

**Comment by mahsan95** [comment]
> It may be easier to understand what's wrong if you give name to every deck.right now, I don't know whether "that one deck I was studying for" is the same than "current test" or "old test" or something else.
> Do you mean that, after you selected cards and added "-2" days to them, the number of due card augmented and the new due cards are cards you didn't s3lect . I don't see how it could be possible

yez! idk how either, it literally applies -2 to midcomp 6, not comp 1 or 2 or whatever which is so annoying!

**Comment by Arthur-Milchior** [comment]
For your information, in the browser, if you look at the "due" column,
you'll see when each card will come back. So it may answer the question
"when will your card come back". It may also help you in figuring out how
many day to remove to this deck.

Do you know how to make a backup of your collection ? You should try
creating a backup of the current collection, removing days to the deck
(let's say that the number of day to remove is the delay between now and
the first card you'll see. I.e. the not new card with the smaller due date)

If it fails again, you can use the backup to cancel this edit

Which makes me realize that I should make "postponing undoable", it would
avoid that your problem reappear with someone else

**Comment by Arthur-Milchior** [comment]
This may be a silly question, but are your sure that the card you want to
review are not suspended ? It may explain why you don't see the card

If you are familar with anki, you probably already have thought of it. But
I don't know how familiear you are.

Can you please describe to me how you ensure that you add/remove day to a
particular deck ?

Regards,
Arthur

**Comment by mahsan95** [comment]
I looked at each of the decks I had rearranged and saw most of those cards are coming back within the next few days. I will just sit on it and see if they actually do come back. I didn’t suspend those cards, I hit the postpone card button and added days, but I assume the days just added together and it added 6 days instead of 2, which would make sense why they’re all gonna start coming back in two days. I will follow back up on Wednesday at this point because i don’t want to mess around with it anymore and cause more chaos to the program, lol. 

Thanks again!

**Comment by Arthur-Milchior** [comment]
Hi

Is there any update ? 
Did all of them come back ?
Can I close this issue ?

**Comment by mahsan95** [comment]
They did, but it’s because I realized that I can’t postpone a specific deck. It postponed all my cards in one, but thanks!

**Comment by Arthur-Milchior** [comment]
You can postpone a specific deck. You need to use the browser. You select a deck in the left column, then you select all cards, and click on «postpone decks» in a menu.
I can easily add «postpone deck» in the gear's option. I just never thought about it

**Comment by mahsan95** [comment]
Oh I never knew this, that would be amazing, thank you!

**Comment by mahsan95** [comment]
When you say in the browser do you mean on the internet or do you mean from the anki app on the computer. Because if I click a deck and then hit tools and postpone it from in there, it will postpone all my cards that day

**Comment by Arthur-Milchior** [comment]
I mean anki's browser.

Anyway, if you update; you should be able to add day using the gear now

**Comment by mahsan95** [comment]
You mean if I get the latest anki or if i redownload the addon
